// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, DTAdType) {
  DTAdTypeIDLE = 0,
  DTAdTypeBANNER = 1,
  DTAdTypeINTERSTITIAL = 2,
  DTAdTypeNATIVE = 3,
  DTAdTypeREWARDED = 4,
  DTAdTypeREWARDED_INTERSTITIAL = 5,
  DTAdTypeAPP_OPEN = 6,
  DTAdTypeMREC = 7,
};

/// Wrapper for DTAdType to allow for nullability.
@interface DTAdTypeBox : NSObject
@property(nonatomic, assign) DTAdType value;
- (instancetype)initWithValue:(DTAdType)value;
@end

typedef NS_ENUM(NSUInteger, DTAdMediation) {
  DTAdMediationIDLE = 0,
  DTAdMediationMOPUB = 1,
  DTAdMediationMAX = 2,
  DTAdMediationHISAVANA = 3,
  DTAdMediationCOMBO = 4,
};

/// Wrapper for DTAdMediation to allow for nullability.
@interface DTAdMediationBox : NSObject
@property(nonatomic, assign) DTAdMediation value;
- (instancetype)initWithValue:(DTAdMediation)value;
@end

typedef NS_ENUM(NSUInteger, DTAdPlatform) {
  DTAdPlatformUNDISCLOSED = 0,
  DTAdPlatformIDLE = 1,
  DTAdPlatformADMOB = 2,
  DTAdPlatformMOPUB = 3,
  DTAdPlatformADCOLONY = 4,
  DTAdPlatformAPPLOVIN = 5,
  DTAdPlatformCHARTBOOST = 6,
  DTAdPlatformFACEBOOK = 7,
  DTAdPlatformINMOBI = 8,
  DTAdPlatformIRONSOURCE = 9,
  DTAdPlatformPANGLE = 10,
  DTAdPlatformSNAP_AUDIENCE_NETWORK = 11,
  DTAdPlatformTAPJOY = 12,
  DTAdPlatformUNITY_ADS = 13,
  DTAdPlatformVERIZON_MEDIA = 14,
  DTAdPlatformVUNGLE = 15,
  DTAdPlatformADX = 16,
  DTAdPlatformCOMBO = 17,
  DTAdPlatformBIGO = 18,
  DTAdPlatformHISAVANA = 19,
  DTAdPlatformAPPLOVIN_EXCHANGE = 20,
  DTAdPlatformLOVINJOYADS = 21,
};

/// Wrapper for DTAdPlatform to allow for nullability.
@interface DTAdPlatformBox : NSObject
@property(nonatomic, assign) DTAdPlatform value;
- (instancetype)initWithValue:(DTAdPlatform)value;
@end


/// The codec used by DTDTAdPigeon.
NSObject<FlutterMessageCodec> *DTDTAdPigeonGetCodec(void);

@protocol DTDTAdPigeon
- (void)reportLoadBeginId:(NSString *)id type:(DTAdType)type platform:(DTAdPlatform)platform seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportLoadEndId:(NSString *)id type:(DTAdType)type platform:(DTAdPlatform)platform duration:(NSNumber *)duration result:(NSNumber *)result seq:(NSString *)seq errorCode:(NSNumber *)errorCode errorMessage:(NSString *)errorMessage properties:(NSDictionary<NSString *, id> *)properties error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportToShowId:(NSString *)id type:(DTAdType)type platform:(DTAdPlatform)platform location:(NSString *)location seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportShowId:(NSString *)id type:(DTAdType)type platform:(DTAdPlatform)platform location:(NSString *)location seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportShowFailedId:(NSString *)id type:(DTAdType)type platform:(DTAdPlatform)platform location:(NSString *)location seq:(NSString *)seq errorCode:(NSNumber *)errorCode errorMessage:(NSString *)errorMessage properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportCloseId:(NSString *)id type:(DTAdType)type platform:(DTAdPlatform)platform location:(NSString *)location seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportClickId:(NSString *)id type:(DTAdType)type platform:(DTAdPlatform)platform location:(NSString *)location seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportRewardedId:(NSString *)id type:(DTAdType)type platform:(DTAdPlatform)platform location:(NSString *)location seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportConversionByClickId:(NSString *)id type:(DTAdType)type platform:(DTAdPlatform)platform location:(NSString *)location seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportConversionByLeftAppId:(NSString *)id type:(DTAdType)type platform:(DTAdPlatform)platform location:(NSString *)location seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportConversionByRewardedId:(NSString *)id type:(DTAdType)type platform:(DTAdPlatform)platform location:(NSString *)location seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportPaidId:(NSString *)id type:(DTAdType)type platform:(DTAdPlatform)platform location:(NSString *)location seq:(NSString *)seq value:(NSString *)value currency:(NSString *)currency precision:(NSString *)precision properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportPaidWithMediationId:(NSString *)id type:(DTAdType)type platform:(DTAdPlatform)platform location:(NSString *)location seq:(NSString *)seq mediation:(DTAdMediation)mediation mediationId:(NSString *)mediationId value:(NSString *)value precision:(NSString *)precision country:(NSString *)country properties:(NSDictionary<NSString *, id> *)properties error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportLeftAppId:(NSString *)id type:(DTAdType)type platform:(DTAdPlatform)platform location:(NSString *)location seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void DTDTAdPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DTDTAdPigeon> *_Nullable api);

NS_ASSUME_NONNULL_END
