// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by DTDTAnalyticsUtilPigeon.
NSObject<FlutterMessageCodec> *DTDTAnalyticsUtilPigeonGetCodec(void);

@protocol DTDTAnalyticsUtilPigeon
- (void)trackTimerStartEventName:(NSString *)eventName error:(FlutterError *_Nullable *_Nonnull)error;
- (void)trackTimerPauseEventName:(NSString *)eventName error:(FlutterError *_Nullable *_Nonnull)error;
- (void)trackTimerResumeEventName:(NSString *)eventName error:(FlutterError *_Nullable *_Nonnull)error;
- (void)trackTimerEndEventName:(NSString *)eventName properties:(nullable NSDictionary<NSString *, id> *)properties error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void DTDTAnalyticsUtilPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DTDTAnalyticsUtilPigeon> *_Nullable api);

NS_ASSUME_NONNULL_END
