// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "dt.g.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

@implementation DTDTLogLevelBox
- (instancetype)initWithValue:(DTDTLogLevel)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

NSObject<FlutterMessageCodec> *DTDTPigeonGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

void DTDTPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DTDTPigeon> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.datatower_ai_core.DTPigeon.initSDK"
        binaryMessenger:binaryMessenger
        codec:DTDTPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(initSDKAppId:url:channel:isDebug:logLevel:commonProperties:error:)], @"DTDTPigeon api (%@) doesn't respond to @selector(initSDKAppId:url:channel:isDebug:logLevel:commonProperties:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_appId = GetNullableObjectAtIndex(args, 0);
        NSString *arg_url = GetNullableObjectAtIndex(args, 1);
        NSString *arg_channel = GetNullableObjectAtIndex(args, 2);
        NSNumber *arg_isDebug = GetNullableObjectAtIndex(args, 3);
        DTDTLogLevel arg_logLevel = [GetNullableObjectAtIndex(args, 4) integerValue];
        NSDictionary<NSString *, id> *arg_commonProperties = GetNullableObjectAtIndex(args, 5);
        FlutterError *error;
        [api initSDKAppId:arg_appId url:arg_url channel:arg_channel isDebug:arg_isDebug logLevel:arg_logLevel commonProperties:arg_commonProperties error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
