// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by DTDTPigeon.
NSObject<FlutterMessageCodec> *DTDTPigeonGetCodec(void);

@protocol DTDTPigeon
- (void)initSDKAppId:(NSString *)appId url:(NSString *)url channel:(NSString *)channel isDebug:(NSNumber *)isDebug logLevel:(NSNumber *)logLevel commonProperties:(NSDictionary<NSString *, id> *)commonProperties error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void DTDTPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DTDTPigeon> *_Nullable api);

NS_ASSUME_NONNULL_END
