// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "dt_analytics_util.g.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

NSObject<FlutterMessageCodec> *DTDTAnalyticsUtilPigeonGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

void DTDTAnalyticsUtilPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DTDTAnalyticsUtilPigeon> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.datatower_ai_core_flutter.DTAnalyticsUtilPigeon.trackTimerStart"
        binaryMessenger:binaryMessenger
        codec:DTDTAnalyticsUtilPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(trackTimerStartEventName:error:)], @"DTDTAnalyticsUtilPigeon api (%@) doesn't respond to @selector(trackTimerStartEventName:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_eventName = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api trackTimerStartEventName:arg_eventName error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.datatower_ai_core_flutter.DTAnalyticsUtilPigeon.trackTimerPause"
        binaryMessenger:binaryMessenger
        codec:DTDTAnalyticsUtilPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(trackTimerPauseEventName:error:)], @"DTDTAnalyticsUtilPigeon api (%@) doesn't respond to @selector(trackTimerPauseEventName:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_eventName = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api trackTimerPauseEventName:arg_eventName error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.datatower_ai_core_flutter.DTAnalyticsUtilPigeon.trackTimerResume"
        binaryMessenger:binaryMessenger
        codec:DTDTAnalyticsUtilPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(trackTimerResumeEventName:error:)], @"DTDTAnalyticsUtilPigeon api (%@) doesn't respond to @selector(trackTimerResumeEventName:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_eventName = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api trackTimerResumeEventName:arg_eventName error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.datatower_ai_core_flutter.DTAnalyticsUtilPigeon.trackTimerEnd"
        binaryMessenger:binaryMessenger
        codec:DTDTAnalyticsUtilPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(trackTimerEndEventName:properties:error:)], @"DTDTAnalyticsUtilPigeon api (%@) doesn't respond to @selector(trackTimerEndEventName:properties:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_eventName = GetNullableObjectAtIndex(args, 0);
        NSDictionary<NSString *, id> *arg_properties = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api trackTimerEndEventName:arg_eventName properties:arg_properties error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
