// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, DTAdTypeDart) {
  DTAdTypeDartIDLE = 0,
  DTAdTypeDartBANNER = 1,
  DTAdTypeDartINTERSTITIAL = 2,
  DTAdTypeDartNATIVE = 3,
  DTAdTypeDartREWARDED = 4,
  DTAdTypeDartREWARDED_INTERSTITIAL = 5,
  DTAdTypeDartAPP_OPEN = 6,
  DTAdTypeDartMREC = 7,
};

/// Wrapper for DTAdTypeDart to allow for nullability.
@interface DTAdTypeDartBox : NSObject
@property(nonatomic, assign) DTAdTypeDart value;
- (instancetype)initWithValue:(DTAdTypeDart)value;
@end

typedef NS_ENUM(NSUInteger, DTAdMediationDart) {
  DTAdMediationDartIDLE = 0,
  DTAdMediationDartMOPUB = 1,
  DTAdMediationDartMAX = 2,
  DTAdMediationDartHISAVANA = 3,
  DTAdMediationDartCOMBO = 4,
  DTAdMediationDartTOPON = 5,
  DTAdMediationDartTRADPLUS = 6,
  DTAdMediationDartTOBID = 7,
};

/// Wrapper for DTAdMediationDart to allow for nullability.
@interface DTAdMediationDartBox : NSObject
@property(nonatomic, assign) DTAdMediationDart value;
- (instancetype)initWithValue:(DTAdMediationDart)value;
@end

typedef NS_ENUM(NSUInteger, DTAdPlatformDart) {
  DTAdPlatformDartUNDISCLOSED = 0,
  DTAdPlatformDartIDLE = 1,
  DTAdPlatformDartADMOB = 2,
  DTAdPlatformDartMOPUB = 3,
  DTAdPlatformDartADCOLONY = 4,
  DTAdPlatformDartAPPLOVIN = 5,
  DTAdPlatformDartCHARTBOOST = 6,
  DTAdPlatformDartFACEBOOK = 7,
  DTAdPlatformDartINMOBI = 8,
  DTAdPlatformDartIRONSOURCE = 9,
  DTAdPlatformDartPANGLE = 10,
  DTAdPlatformDartSNAP_AUDIENCE_NETWORK = 11,
  DTAdPlatformDartTAPJOY = 12,
  DTAdPlatformDartUNITY_ADS = 13,
  DTAdPlatformDartVERIZON_MEDIA = 14,
  DTAdPlatformDartVUNGLE = 15,
  DTAdPlatformDartADX = 16,
  DTAdPlatformDartCOMBO = 17,
  DTAdPlatformDartBIGO = 18,
  DTAdPlatformDartHISAVANA = 19,
  DTAdPlatformDartAPPLOVIN_EXCHANGE = 20,
  DTAdPlatformDartMINTEGRAL = 21,
  DTAdPlatformDartLIFTOFF = 22,
  DTAdPlatformDartA4G = 23,
  DTAdPlatformDartGOOGLE_AD_MANAGER = 24,
  DTAdPlatformDartFYBER = 25,
  DTAdPlatformDartMAIO = 26,
  DTAdPlatformDartCRITEO = 27,
  DTAdPlatformDartMYTARGET = 28,
  DTAdPlatformDartOGURY = 29,
  DTAdPlatformDartAPPNEXT = 30,
  DTAdPlatformDartKIDOZ = 31,
  DTAdPlatformDartSMAATO = 32,
  DTAdPlatformDartSTART_IO = 33,
  DTAdPlatformDartVERVE = 34,
  DTAdPlatformDartLOVINJOYADS = 35,
  DTAdPlatformDartYANDEX = 36,
  DTAdPlatformDartREKLAMUP = 37,
};

/// Wrapper for DTAdPlatformDart to allow for nullability.
@interface DTAdPlatformDartBox : NSObject
@property(nonatomic, assign) DTAdPlatformDart value;
- (instancetype)initWithValue:(DTAdPlatformDart)value;
@end


/// The codec used by DTDTAdPigeon.
NSObject<FlutterMessageCodec> *DTDTAdPigeonGetCodec(void);

@protocol DTDTAdPigeon
- (void)reportLoadBeginId:(NSString *)id type:(DTAdTypeDart)type platform:(DTAdPlatformDart)platform seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportLoadEndId:(NSString *)id type:(DTAdTypeDart)type platform:(DTAdPlatformDart)platform duration:(NSNumber *)duration result:(NSNumber *)result seq:(NSString *)seq errorCode:(NSNumber *)errorCode errorMessage:(NSString *)errorMessage properties:(NSDictionary<NSString *, id> *)properties error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportToShowId:(NSString *)id type:(DTAdTypeDart)type platform:(DTAdPlatformDart)platform location:(NSString *)location seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportShowId:(NSString *)id type:(DTAdTypeDart)type platform:(DTAdPlatformDart)platform location:(NSString *)location seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportShowFailedId:(NSString *)id type:(DTAdTypeDart)type platform:(DTAdPlatformDart)platform location:(NSString *)location seq:(NSString *)seq errorCode:(NSNumber *)errorCode errorMessage:(NSString *)errorMessage properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportCloseId:(NSString *)id type:(DTAdTypeDart)type platform:(DTAdPlatformDart)platform location:(NSString *)location seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportClickId:(NSString *)id type:(DTAdTypeDart)type platform:(DTAdPlatformDart)platform location:(NSString *)location seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportRewardedId:(NSString *)id type:(DTAdTypeDart)type platform:(DTAdPlatformDart)platform location:(NSString *)location seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportConversionByClickId:(NSString *)id type:(DTAdTypeDart)type platform:(DTAdPlatformDart)platform location:(NSString *)location seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportConversionByLeftAppId:(NSString *)id type:(DTAdTypeDart)type platform:(DTAdPlatformDart)platform location:(NSString *)location seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportConversionByRewardedId:(NSString *)id type:(DTAdTypeDart)type platform:(DTAdPlatformDart)platform location:(NSString *)location seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportPaidId:(NSString *)id type:(DTAdTypeDart)type platform:(DTAdPlatformDart)platform location:(NSString *)location seq:(NSString *)seq value:(NSString *)value currency:(NSString *)currency precision:(NSString *)precision properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportPaidWithMediationId:(NSString *)id type:(DTAdTypeDart)type platform:(DTAdPlatformDart)platform location:(NSString *)location seq:(NSString *)seq mediation:(DTAdMediationDart)mediation mediationId:(NSString *)mediationId value:(NSString *)value precision:(NSString *)precision country:(NSString *)country properties:(NSDictionary<NSString *, id> *)properties error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportLeftAppId:(NSString *)id type:(DTAdTypeDart)type platform:(DTAdPlatformDart)platform location:(NSString *)location seq:(NSString *)seq properties:(NSDictionary<NSString *, id> *)properties entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void DTDTAdPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DTDTAdPigeon> *_Nullable api);

NS_ASSUME_NONNULL_END
