// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by DTDTIapPigeon.
NSObject<FlutterMessageCodec> *DTDTIapPigeonGetCodec(void);

@protocol DTDTIapPigeon
- (void)reportPurchaseSuccessOrder:(NSString *)order sku:(NSString *)sku price:(NSNumber *)price currency:(NSString *)currency properties:(nullable NSDictionary<NSString *, id> *)properties error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void DTDTIapPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DTDTIapPigeon> *_Nullable api);

NS_ASSUME_NONNULL_END
